import GObject from 'gi://GObject'
import GLib from 'gi://GLib'
import St from 'gi://St'

import {clawdAnim} from '../shared/labels.mjs'

// Sprite sheet metadata generated by scripts/build-clawd-sprites.py, imported
// as an ES module rather than read as JSON. The KDE side had to make this
// switch because Qt 6 blocks file:// XHR; importing works in both engines and
// needs no filesystem permission, so both frontends now consume one module.
import {FRAMES} from '../shared/clawd/frames.mjs'

// GNOME Shell 49's ui/animation.js exports only `Spinner` (a rotating
// spinner icon) -- the `Animation`/`AnimatedIcon` sprite-sheet classes this
// plan originally targeted do not exist on this version; they were removed
// upstream. Per the plan's documented fallback, this hand-rolls the same
// horizontal-sprite-sheet technique with St's background-position/
// background-size CSS support: one clip rect per frame, stepped by a timer.
//
// Animated Clawd, played from the same sprite sheets the plasmoid uses so
// both frontends show identical frames at an identical rate.
export const ClawdSprite = GObject.registerClass(
class ClawdSprite extends St.Widget {
    _init(extPath, size) {
        // x/y_expand: false and clip_to_allocation both guard against the
        // same failure mode: if this actor's allocation ever ends up wider
        // than `size` (a stretching layout, a parent with spare space to
        // give away), the background-image sprite sheet tiles across the
        // extra width instead of showing one clipped frame -- observed live
        // as several repeated Clawd frames in the panel. clip_to_allocation
        // is a Clutter.Actor property, not CSS, so it's set here rather than
        // in stylesheet.css, where St's theme parser may not recognise it.
        super._init({
            style_class: 'claude-clawd',
            x_expand: false, y_expand: false,
            clip_to_allocation: true,
        })
        this._extPath = extPath
        this._size = size
        this.set_size(size, size)

        this._current = null
        this._frame = 0
        this._frameCount = 0
        this._interval = 0
        this._baseStyle = ''
        this._timerId = 0
        // See ShimmerLabel: the 'destroy' signal fires on every disposal
        // path, unlike our own destroy() override which only runs when
        // something calls .destroy() explicitly.
        this.connect('destroy', () => this._stopTimer())

        this.setState('idle', null)
    }

    setState(state, tool) {
        const name = clawdAnim(state, tool)
        if (name === this._current)
            return
        this._current = name
        this._frame = 0
        this._stopTimer()

        const info = FRAMES[name]
        if (!info) {
            this.style = null
            return
        }
        this._frameCount = info.frames
        this._interval = info.interval_ms

        const path = GLib.build_filenamev(
            [this._extPath, 'shared', 'clawd', `${name}.png`])
        // Scaling the whole sheet to frameCount * size keeps every frame
        // exactly `size` px wide with no distortion, since each source frame
        // is square and the sheet's aspect ratio is frameCount:1.
        this._baseStyle =
            `background-image: url("file://${path}"); ` +
            `background-size: ${this._frameCount * this._size}px ${this._size}px; ` +
            'background-repeat: no-repeat;'
        this._applyFrame()
        this._startTimer()
    }

    _applyFrame() {
        const offset = -(this._frame * this._size)
        this.style = `${this._baseStyle} background-position: ${offset}px 0px;`
    }

    _startTimer() {
        if (this._timerId || this._frameCount <= 1)
            return
        this._timerId = GLib.timeout_add(GLib.PRIORITY_DEFAULT, this._interval, () => {
            this._frame = (this._frame + 1) % this._frameCount
            this._applyFrame()
            return GLib.SOURCE_CONTINUE
        })
    }

    _stopTimer() {
        if (this._timerId) {
            GLib.Source.remove(this._timerId)
            this._timerId = 0
        }
    }

    pause() {
        this._stopTimer()
    }

    resume() {
        this._startTimer()
    }

    destroy() {
        this._stopTimer()
        super.destroy()
    }
})
